// All 10 IPL 2025 teams with their ESPN cricket team IDs
// and official colors
export const IPL_TEAMS = [
  {
    id: 'mi',
    name: 'Mumbai Indians',
    shortName: 'MI',
    city: 'Mumbai',
    color: '#004BA0',
    color2: '#D1AB3E',
    logo: 'https://cricsheet.org/images/teams/mi.png',
    ground: 'Wankhede Stadium',
    titles: 5,
  },
  {
    id: 'csk',
    name: 'Chennai Super Kings',
    shortName: 'CSK',
    city: 'Chennai',
    color: '#F9CD05',
    color2: '#0081E9',
    logo: 'https://cricsheet.org/images/teams/csk.png',
    ground: 'MA Chidambaram Stadium',
    titles: 5,
  },
  {
    id: 'rcb',
    name: 'Royal Challengers Bengaluru',
    shortName: 'RCB',
    city: 'Bengaluru',
    color: '#EC1C24',
    color2: '#000000',
    logo: 'https://cricsheet.org/images/teams/rcb.png',
    ground: 'M. Chinnaswamy Stadium',
    titles: 0,
  },
  {
    id: 'kkr',
    name: 'Kolkata Knight Riders',
    shortName: 'KKR',
    city: 'Kolkata',
    color: '#3A225D',
    color2: '#B3A123',
    logo: 'https://cricsheet.org/images/teams/kkr.png',
    ground: 'Eden Gardens',
    titles: 3,
  },
  {
    id: 'dc',
    name: 'Delhi Capitals',
    shortName: 'DC',
    city: 'Delhi',
    color: '#0078BC',
    color2: '#EF1B23',
    logo: 'https://cricsheet.org/images/teams/dc.png',
    ground: 'Arun Jaitley Stadium',
    titles: 0,
  },
  {
    id: 'pbks',
    name: 'Punjab Kings',
    shortName: 'PBKS',
    city: 'Mohali',
    color: '#ED1B24',
    color2: '#A7A9AC',
    logo: 'https://cricsheet.org/images/teams/pbks.png',
    ground: 'IS Bindra Stadium',
    titles: 0,
  },
  {
    id: 'rr',
    name: 'Rajasthan Royals',
    shortName: 'RR',
    city: 'Jaipur',
    color: '#EA1A85',
    color2: '#254AA5',
    logo: 'https://cricsheet.org/images/teams/rr.png',
    ground: 'Sawai Mansingh Stadium',
    titles: 1,
  },
  {
    id: 'srh',
    name: 'Sunrisers Hyderabad',
    shortName: 'SRH',
    city: 'Hyderabad',
    color: '#F7A721',
    color2: '#E95B10',
    logo: 'https://cricsheet.org/images/teams/srh.png',
    ground: 'Rajiv Gandhi International Stadium',
    titles: 1,
  },
  {
    id: 'lsg',
    name: 'Lucknow Super Giants',
    shortName: 'LSG',
    city: 'Lucknow',
    color: '#A72056',
    color2: '#FFCC00',
    logo: 'https://cricsheet.org/images/teams/lsg.png',
    ground: 'BRSABV Ekana Cricket Stadium',
    titles: 0,
  },
  {
    id: 'gt',
    name: 'Gujarat Titans',
    shortName: 'GT',
    city: 'Ahmedabad',
    color: '#1C1C6E',
    color2: '#00BFFF',
    logo: 'https://cricsheet.org/images/teams/gt.png',
    ground: 'Narendra Modi Stadium',
    titles: 1,
  },
]